[[target]]
name = "yilinx"
description = "Generate bitstreams for Yilinx FPGAs"
command = ["python3", "yilinx.py"]
fileset.pinout = "*.ydc"

[[target]]
name = "ninja"
command = ["python3", "ninja.py"]

[build]
default-target = "yilinx"

[publish]
default-channels = ["huron"]
