[[target]]
name = "yilinx"
description = "Generate bitstreams for Yilinx FPGAs"
command = "python"
fileset.pinout = "*.ydc"
args = ["yilinx.py"]


[build]
default-target = "yilinx"


[[protocol]]
name = "gitit"
description = "Download ip using git"
command = "git"
args = ["clone", "{{ orbit.ip.source.url }}"]